#!/usr/bin/env bash

require () {
	for i
	do
		if ! command -v "$i" > /dev/null
		then
			echo command $i not found, please install
			exit 1
		fi
	done
}

main () {
	cd /var/www/hsg-ip # $(readlink -f $0 | xargs dirname | xargs dirname)
	dig -tany hsg.rocks |
		grep -ve ^$ -ve '^;' -ve registrar-servers |
		xargs | cut -d\  -f1,5 > dig.data
	git add dig.data
	git commit --author=CJ -m "$(cat dig.data)"
	git push github master
}

require dig grep xargs tee git
main
