#!/usr/bin/env bash

require () {
	for i
	do
		if ! command -v "$i" > /dev/null
		then
			echo command $i not found, please install
			exit 1
		fi
	done
}

main () {
	curl curlmyip.com --silent --output /var/www/hsg-ip/dig.data
	git add dig.data
	git commit --author=CJ -m "$(cat dig.data)"
	git push github master
}

require curl grep xargs tee git
main
